import re
from sentence_transformers import SentenceTransformer, util

sbert_model = SentenceTransformer("all-MiniLM-L6-v2")

TOPICS = {
    "Technology": [
        "tech",
        "information technology",
        "software",
        "hardware",
        "artificial intelligence",
        "AI",
        "machine learning",
        "ML",
        "deep learning",
        "neural networks",
        "LLM",
        "large language models",
        "generative AI",
        "computer science",
        "coding",
        "programming",
        "cybersecurity",
        "cloud computing",
        "SaaS",
        "blockchain",
        "web3",
        "metaverse",
        "robotics",
        "automation",
        "data science",
        "big data",
        "IoT",
        "internet of things",
        "quantum computing",
        "startup",
        "tech industry",
        "digital transformation",
        "API",
        "devops",
        "agile",
        "open source",
    ],
    "Science": [
        "research",
        "scientific",
        "biology",
        "physics",
        "chemistry",
        "experiment",
        "astronomy",
        "genetics",
        "neuroscience",
        "ecology",
        "climate science",
        "paleontology",
        "zoology",
        "botany",
        "geology",
        "scientific method",
        "peer review",
        "lab",
        "laboratory",
        "hypothesis",
        "theory",
        "discovery",
        "innovation",
        "STEM",
        "scientific breakthrough",
        "environmental science",
        "marine biology",
        "biotechnology",
        "CRISPR",
        "nanotechnology",
    ],
    "Politics": [
        "government",
        "election",
        "policy",
        "congress",
        "parliament",
        "democracy",
        "authoritarianism",
        "diplomacy",
        "foreign policy",
        "legislation",
        "bill",
        "senate",
        "political party",
        "campaign",
        "voting",
        "ballot",
        "activism",
        "protest",
        "civil rights",
        "human rights",
        "geopolitics",
        "bureaucracy",
        "public administration",
        "political science",
        "supreme court",
        "judiciary",
        "impeachment",
        "referendum",
        "governance",
        "lobbying",
    ],
    "Economics": [
        "economy",
        "finance",
        "markets",
        "inflation",
        "central bank",
        "GDP",
        "recession",
        "depression",
        "monetary policy",
        "fiscal policy",
        "interest rates",
        "unemployment",
        "trade",
        "globalization",
        "tariffs",
        "economic growth",
        "budget",
        "deficit",
        "stock market",
        "crypto",
        "cryptocurrency",
        "Bitcoin",
        "blockchain economics",
        "microeconomics",
        "macroeconomics",
        "wealth inequality",
        "taxation",
        "investment",
        "venture capital",
        "hedge fund",
        "economic sanctions",
        "supply chain",
        "commodities",
        "consumer spending",
    ],
    "Culture": [
        "social",
        "customs",
        "tradition",
        "cultural",
        "identity",
        "heritage",
        "ethnicity",
        "language",
        "dialect",
        "ritual",
        "folklore",
        "values",
        "norms",
        "sociology",
        "anthropology",
        "cultural exchange",
        "multiculturalism",
        "cultural appropriation",
        "pop culture",
        "subculture",
        "generational",
        "worldview",
        "belief systems",
        "cultural preservation",
        "indigenous",
        "cultural diversity",
        "cultural norms",
        "cultural identity",
    ],
    "Entertainment": [
        "movie",
        "tv",
        "film",
        "celebrity",
        "show",
        "music",
        "streaming",
        "Netflix",
        "Hulu",
        "Disney+",
        "box office",
        "Oscars",
        "Grammys",
        "Emmy",
        "award show",
        "blockbuster",
        "indie film",
        "concert",
        "album",
        "playlist",
        "podcast",
        "influencer",
        "social media star",
        "reality TV",
        "gaming",
        "video games",
        "esports",
        "anime",
        "comics",
        "superhero",
        "fan fiction",
        "fandom",
        "trailer",
        "b-roll",
        "behind the scenes",
    ],
    "Lifestyle": [
        "travel",
        "food",
        "home",
        "fashion",
        "daily life",
        "wellness",
        "self-care",
        "minimalism",
        "sustainability",
        "eco-friendly",
        "interior design",
        "DIY",
        "crafts",
        "parenting",
        "pet care",
        "hobbies",
        "outdoor activities",
        "urban living",
        "remote work",
        "digital nomad",
        "work-life balance",
        "mindfulness",
        "yoga",
        "meditation",
        "personal finance",
        "budgeting",
        "meal prep",
        "home cooking",
        "thrifting",
        "slow fashion",
        "van life",
    ],
    "Health": [
        "medicine",
        "healthcare",
        "disease",
        "fitness",
        "wellness",
        "mental health",
        "therapy",
        "counseling",
        "pandemic",
        "vaccines",
        "public health",
        "nutrition",
        "diet",
        "exercise",
        "chronic illness",
        "disability",
        "pharmaceuticals",
        "clinical trials",
        "telemedicine",
        "health insurance",
        "obesity",
        "addiction",
        "sleep",
        "stress",
        "preventive care",
        "holistic health",
        "alternative medicine",
        "medical research",
        "doctor",
        "hospital",
        "nursing",
        "epidemiology",
        "longevity",
        "biohacking",
    ],
    "Education": [
        "school",
        "university",
        "learning",
        "teaching",
        "curriculum",
        "online learning",
        "e-learning",
        "MOOC",
        "STEM education",
        "literacy",
        "critical thinking",
        "pedagogy",
        "edtech",
        "classroom",
        "student",
        "teacher",
        "professor",
        "academic",
        "research paper",
        "thesis",
        "dissertation",
        "standardized testing",
        "homeschooling",
        "unschooling",
        "vocational training",
        "scholarship",
        "tuition",
        "student debt",
        "lifelong learning",
        "early childhood education",
        "special education",
        "educational equity",
        "digital literacy",
    ],
    "Relationships": [
        "dating",
        "friendship",
        "family",
        "marriage",
        "divorce",
        "breakup",
        "love",
        "intimacy",
        "communication",
        "conflict resolution",
        "boundaries",
        "emotional support",
        "long-distance",
        "cohabitation",
        "parenting",
        "siblings",
        "extended family",
        "social connection",
        "loneliness",
        "attachment",
        "trust",
        "commitment",
        "polyamory",
        "LGBTQ+ relationships",
        "dating apps",
        "Tinder",
        "ghosting",
        "modern romance",
        "interpersonal",
    ],
    "Art": [
        "painting",
        "sculpture",
        "gallery",
        "artist",
        "visual art",
        "drawing",
        "printmaking",
        "photography",
        "digital art",
        "NFT art",
        "installation",
        "performance art",
        "conceptual art",
        "art history",
        "museum",
        "curator",
        "art critic",
        "aesthetic",
        "creativity",
        "design",
        "graphic design",
        "street art",
        "graffiti",
        "modern art",
        "contemporary art",
        "renaissance",
        "impressionism",
        "abstract",
        "figurative",
        "mixed media",
    ],
    "Humor": [
        "joke",
        "satire",
        "funny",
        "comedy",
        "hahaha",
        "meme",
        "internet humor",
        "stand-up",
        "sketch comedy",
        "parody",
        "irony",
        "sarcasm",
        "wit",
        "banter",
        "roast",
        "dark humor",
        "dad jokes",
        "puns",
        "slapstick",
        "comedian",
        "laughter",
        "humorous",
        "light-hearted",
        "tongue-in-cheek",
        "absurdism",
        "situational comedy",
        "cringe comedy",
        "observational humor",
        "comic relief",
    ],
}


def clean_text(text):
    text = re.sub(r"http\S+|\S+@\S+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def classify_by_embedding(text, topics=TOPICS, return_all=False):
    text = clean_text(text)
    emb_text = sbert_model.encode(text, convert_to_tensor=True)
    best_topic = None
    best_score = -1.0
    scores = {}
    for topic, seeds in topics.items():
        seeds_to_embed = [topic] + seeds
        emb_seeds = sbert_model.encode(seeds_to_embed, convert_to_tensor=True)
        sims = util.cos_sim(emb_text, emb_seeds)[0]
        max_sim = float(sims.max())
        scores[topic] = max_sim
        if max_sim > best_score:
            best_score = max_sim
            best_topic = topic
    if return_all:
        return best_topic, best_score, scores
    return best_topic, best_score
